import Head from 'next/head'
import React, {useState} from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useLoading, Audio,
  BallTriangle,
  Bars,
  Circles,
  Grid,
  Hearts,
  Oval,
  Puff,
  Rings,
  SpinningCircles,
  TailSpin,
  ThreeDots, } from '@agney/react-loading';
import {Loader} from '../src/components/Items/Loader/Loader'
// import '../src/components/Items/Button/button.css'

import { Button } from '../src/components/Items/Button/Button'

export default function Home() {
const[load, setLoad] = useState(true)

  const handleLoader = () => {
    setLoad(false)
    setTimeout(() => {
      setLoad(true)
    },2000)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {load && (
      <div style={{padding:20}}>
      <Button onClick={handleLoader} className="storybook-button storybook-button--large Primary" label="Checks"></Button>
      </div>
      )}
      {!load && (
        <Loader width="100" />
      )}

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
